/**
 * Electorate name handling and boundary-dataset selection.
 *
 * Electorate boundaries are redrawn each cycle, so the map's GeoJSON is keyed
 * by election year (`public/boundaries/<year>/…`). The client picks the set
 * whose electorate names match the results it is actually rendering: the app
 * runs against the 2023 feed by default but is built for the 2026 general
 * election, and 10 general electorates changed name or disappeared between
 * the two.
 */

export type BoundaryKind = 'general' | 'maori';

/** `public/boundaries/index.json`, generated by the fetch script. */
export type BoundaryManifest = {
  years: Record<string, Partial<Record<BoundaryKind, string[]>>>;
};

export const BOUNDARY_MANIFEST_PATH = '/boundaries/index.json';

/**
 * The seven Māori electorates.
 *
 * Names are unchanged between the 2023 and 2026 cycles — the Representation
 * Commission adjusted the boundaries of three of them but renamed none — so a
 * static set is correct for both. `electorates.test.ts` asserts it against
 * every boundary manifest on disk so a future rename cannot drift quietly.
 */
export const MAORI_ELECTORATES = new Set([
  'Hauraki-Waikato',
  'Ikaroa-Rāwhiti',
  'Tāmaki Makaurau',
  'Te Tai Hauāuru',
  'Te Tai Tokerau',
  'Te Tai Tonga',
  'Waiariki',
]);

const MAORI_ELECTORATE_KEYS = new Set(
  [...MAORI_ELECTORATES].map(normalizeElectorateName)
);

/**
 * Whether an electorate is a Māori electorate, tolerant of macron and
 * punctuation differences in the source name (`Ikaroa-Rawhiti` still counts).
 * The general/Māori split drives both the map layer and the electorate list,
 * so a name variant must not silently file a Māori seat under general.
 */
export function isMaoriElectorate(name: string): boolean {
  return MAORI_ELECTORATE_KEYS.has(normalizeElectorateName(name));
}

export function boundaryGeoJsonPath(year: string, kind: BoundaryKind): string {
  return `/boundaries/${year}/${kind}-electorates.geojson`;
}

/**
 * Compare electorate names the way a reader would: ignore macrons and case,
 * and treat hyphens/punctuation as spaces.
 *
 * This matters because the Electoral Commission's XML feed and Stats NZ's
 * boundary data both publish macronised names (`Ōtāhuhu`, `Māngere`,
 * `Kaikōura`) but also publish ASCII variants, and a feed change on election
 * night would otherwise silently leave electorates uncoloured on the map.
 */
export function normalizeElectorateName(name: string): string {
  return name
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

export type BoundaryYearChoice = {
  year: string | null;
  /** Fraction of live electorates covered by the chosen year's boundary names. */
  coverage: number;
  /** Live electorates with no boundary in the chosen year. */
  unmatched: string[];
};

function namesForYear(manifest: BoundaryManifest, year: string): string[] {
  const entry = manifest.years[year];
  if (!entry) return [];
  return [...(entry.general ?? []), ...(entry.maori ?? [])];
}

/**
 * Pick the boundary dataset to draw.
 *
 * `preferredYear` (VITE_ELECTION_YEAR) wins when that year is available, so
 * deployments can pin the cycle. Otherwise the year whose names best cover the
 * live results is used, which keeps `npm run dev` against 2023 results correct
 * without any configuration.
 */
export function selectBoundaryYear(
  manifest: BoundaryManifest,
  liveNames: string[],
  preferredYear?: string
): BoundaryYearChoice {
  const years = Object.keys(manifest.years).sort();
  if (years.length === 0) {
    return { year: null, coverage: 0, unmatched: liveNames };
  }

  const score = (year: string) => {
    const known = new Set(
      namesForYear(manifest, year).map(normalizeElectorateName)
    );
    const unmatched = liveNames.filter(
      (name) => !known.has(normalizeElectorateName(name))
    );
    return {
      year,
      coverage:
        liveNames.length > 0 ? 1 - unmatched.length / liveNames.length : 0,
      unmatched,
    };
  };

  if (preferredYear && years.includes(preferredYear)) {
    return score(preferredYear);
  }

  // No live results yet: fall back to the newest dataset.
  if (liveNames.length === 0) {
    return { year: years[years.length - 1]!, coverage: 0, unmatched: [] };
  }

  let best = score(years[0]!);
  for (const year of years.slice(1)) {
    const candidate = score(year);
    if (candidate.coverage > best.coverage) best = candidate;
  }
  return best;
}

export type BoundaryMatchReport = {
  /** Electorates present in the results but missing from the boundary file. */
  unmatchedLive: string[];
  /** Boundary features with no matching result (e.g. renamed electorates). */
  orphanPolygons: string[];
};

/**
 * Compare the electorates being displayed with the polygons being drawn, for
 * one boundary kind. Anything unmatched means the boundary file is from the
 * wrong cycle and the map cannot be trusted.
 */
export function compareBoundaryNames(
  liveNames: string[],
  polygonNames: string[]
): BoundaryMatchReport {
  const polygonKeys = new Set(polygonNames.map(normalizeElectorateName));
  const liveKeys = new Set(liveNames.map(normalizeElectorateName));

  return {
    unmatchedLive: liveNames.filter(
      (name) => !polygonKeys.has(normalizeElectorateName(name))
    ),
    orphanPolygons: polygonNames.filter(
      (name) => !liveKeys.has(normalizeElectorateName(name))
    ),
  };
}

export type GeoBounds = {
  minLat: number;
  maxLat: number;
  minLon: number;
  maxLon: number;
};

/**
 * New Zealand's main islands — and the near-shore islands that belong to
 * mainland electorates, out to Great Barrier — all sit in this longitude band.
 *
 * Island groups east of the antimeridian fall outside it, because they are
 * stored as negative longitudes rather than >180: the Chatham Islands are
 * ≈ -176.5°, the Kermadecs ≈ -177.9°.
 */
const MAIN_ISLAND_LON_MIN = 165;
const MAIN_ISLAND_LON_MAX = 180;

/**
 * Widest longitude span that can reasonably be one electorate's viewport. The
 * largest electorate, Te Tai Tonga, is about 9° across, so anything approaching
 * a full turn means the geometry wraps the antimeridian.
 */
const MAX_FOCUS_LON_SPAN = 30;

type Point = [number, number];

/** Split a geometry into its polygons, whatever its declared type. */
function geometryPolygons(geometry: {
  type: string;
  coordinates?: unknown;
}): unknown[] {
  if (geometry.type === 'MultiPolygon') {
    return Array.isArray(geometry.coordinates)
      ? (geometry.coordinates as unknown[])
      : [];
  }
  if (geometry.type === 'Polygon') return [geometry.coordinates];
  return [];
}

function polygonPositions(polygon: unknown): Point[] {
  if (!Array.isArray(polygon)) return [];
  const positions: Point[] = [];
  for (const ring of polygon) {
    if (!Array.isArray(ring)) continue;
    for (const position of ring) {
      if (
        Array.isArray(position) &&
        typeof position[0] === 'number' &&
        typeof position[1] === 'number'
      ) {
        positions.push([position[0], position[1]]);
      }
    }
  }
  return positions;
}

function boundsOf(positions: Point[]): GeoBounds {
  let minLat = Infinity;
  let maxLat = -Infinity;
  let minLon = Infinity;
  let maxLon = -Infinity;
  for (const [lon, lat] of positions) {
    if (lat < minLat) minLat = lat;
    if (lat > maxLat) maxLat = lat;
    if (lon < minLon) minLon = lon;
    if (lon > maxLon) maxLon = lon;
  }
  return { minLat, maxLat, minLon, maxLon };
}

/**
 * The box the map should zoom to when an electorate is selected.
 *
 * Taking the bounds of every polygon is wrong for electorates that include an
 * island group across the antimeridian. Both Te Tai Tonga and Wellington Bays
 * take in the Chatham Islands, so their union spans ~352° of longitude and
 * `fitBounds` zooms out to the whole Pacific instead of in to the electorate —
 * the larger the electorate, the further out it went.
 *
 * So: fit the polygons in the main-island band, and ignore outlying groups.
 * They are still drawn — they just do not define the viewport, because the
 * mainland is where the electorate and its voters are. Returns `null` when
 * there is nothing sensible to fit, and the caller keeps the country view.
 */
export function focusBounds(geometry: {
  type: string;
  /** Absent on a GeometryCollection, which has nothing to fit anyway. */
  coordinates?: unknown;
}): GeoBounds | null {
  const polygons = geometryPolygons(geometry);
  if (polygons.length === 0) return null;

  const withBounds = polygons
    .map((polygon) => polygonPositions(polygon))
    .filter((positions) => positions.length > 0)
    .map((positions) => ({ positions, bounds: boundsOf(positions) }));
  if (withBounds.length === 0) return null;

  const onMainIslands = withBounds.filter(
    ({ bounds }) =>
      !(
        bounds.maxLon < MAIN_ISLAND_LON_MIN ||
        bounds.minLon > MAIN_ISLAND_LON_MAX
      )
  );
  // If the whole feature is outside the band, use it rather than nothing.
  const considered = onMainIslands.length > 0 ? onMainIslands : withBounds;

  const positions = considered.flatMap((entry) => entry.positions);
  const bounds = boundsOf(positions);
  if (bounds.maxLon - bounds.minLon > MAX_FOCUS_LON_SPAN) return null;
  return bounds;
}
